language: generic

env:
  global:
  - '$HOME/.local/bin/:$PATH'

cache:
  directories:
  - '$HOME/.stack'
  - '$HOME/.local'
  - '.stack-work'

before_install:
- 'curl -Lo stack.tar.gz https://www.stackage.org/stack/linux-x86_64-static'
- 'tar xzf stack.tar.gz'
- 'mkdir -p "$HOME/.local/bin"'
- 'cp stack-*-linux-x86_64-static/stack "$HOME/.local/bin/"'

script:
- 'bash deploy/build.sh'
- 'bash deploy/deploy.sh'
