resolver: lts-11.0

extra-package-dbs: []
packages:
- '.'

flags:
  hakyll:
    usePandoc: false

extra-deps:
- 'hakyll-4.12.1.0'
- git: https://github.com/haskell/haddock.git
  commit: 8064353244842c8a5b04d99cd5e6bb6430a9b51c
  subdirs:
  - 'haddock-library'
